const styleSheet = {
  backgroundColor: {
    type: "Color",
  },
  color: {
    type: "Color",
  },
  borders: {
    borderColor: {
      type: "Color",
    },
    borderWidth: {
      type: "Unit",
      min: 0,
      max: 10,
      step: 1,
      unit: "rem",
    },
    borderRadius: {
      type: "Unit",
      min: 0,
      max: 50,
      step: 1,
      unit: "rem",
    },
    borderTopLeftRadius: {
      type: "Unit",
      min: 0,
      max: 50,
      step: 1,
      unit: "rem",
    },
    borderTopRightRadius: {
      type: "Unit",
      min: 0,
      max: 50,
      step: 1,
      unit: "rem",
    },
    borderBottomLeftRadius: {
      type: "Unit",
      min: 0,
      max: 50,
      step: 1,
      unit: "rem",
    },
    borderBottomRightRadius: {
      type: "Unit",
      min: 0,
      max: 50,
      step: 1,
      unit: "rem",
    },
  },
  width: {
    type: "Unit",
    min: 0,
    max: 100,
    step: 1,
    unit: "%",
  },
  height: {
    type: "Unit",
    min: 0,
    max: 100,
    step: 1,
    unit: "%",
  },
  paddings: {
    padding: {
      type: "Unit",
      min: 0,
      max: 10,
      step: 1,
      unit: "rem",
    },
    paddingTop: {
      type: "Unit",
      min: 0,
      max: 10,
      step: 1,
      unit: "rem",
    },
    paddingLeft: {
      type: "Unit",
      min: 0,
      max: 10,
      step: 1,
      unit: "rem",
    },
    paddingRight: {
      type: "Unit",
      min: 0,
      max: 10,
      step: 1,
      unit: "rem",
    },
    paddingBottom: {
      type: "Unit",
      min: 0,
      max: 10,
      step: 1,
      unit: "rem",
    },
  },
  margins: {
    margin: {
      type: "Unit",
      min: 0,
      max: 10,
      step: 1,
      unit: "rem",
    },
    marginTop: {
      type: "Unit",
      min: 0,
      max: 10,
      step: 1,
      unit: "rem",
    },
    marginLeft: {
      type: "Unit",
      min: 0,
      max: 10,
      step: 1,
      unit: "rem",
    },
    marginRight: {
      type: "Unit",
      min: 0,
      max: 10,
      step: 1,
      unit: "rem",
    },
    marginBottom: {
      type: "Unit",
      min: 0,
      max: 10,
      step: 1,
      unit: "rem",
    },
  },
};

export default styleSheet;
