const types = {
  TOGGLE_EDITOR: "TOGGLE_EDITOR",
  TOGGLE_COMPONENT_DRAWER: "TOGGLE_COMPONENT_DRAWER",
  TOGGLE_CONTEXT_MENU: "TOGGLE_CONTEXT_MENU",
  MOUSE_POS_CAPTURE: "MOUSE_POS_CAPTURE",
};

export default types;
